### ISSUE TITLE
CmakeFileLists

### ISSUE THREAD

**Issue by CodeLearner4App** [thinkerleolee/FSRCNN-OpenCV#2]
hi，作者你好，能否给出项目的CmakeFileLists？我水平比较差，一直写不对，先谢谢了。

**Comment by thinkerleolee** [comment]
您好：
    因为目前只在Windows 10 X64下用Visual Studio 2017开发此项目，没有使用Cmake。所以只上传了vs的项目文件，所有的依赖库和代码均已经上传，您可以对照着vs的配置文件写出自己的Cmake和CmakeFileLists文件。
                                                                                      Leo
________________________________
发件人: CodeLearner4App <notifications@github.com>
发送时间: 2019年5月16日 14:06
收件人: thinkerleolee/FSRCNN-OpenCV
抄送: Subscribed
主题: [thinkerleolee/FSRCNN-OpenCV] CmakeFileLists (#2)


hi，作者你好，能否给出项目的CmakeFileLists？我水平比较差，一直写不对，先谢谢了。

―

**Comment by CodeLearner4App** [comment]
好的，感谢您的回复。
